### ISSUE TITLE
internal cmpl error: no suitable index value in SetIterator::isScalarIn()

### ISSUE THREAD

**Issue by snicolai** [coin-or/Cmpl#2]
I'm attempting to convert a simple model from cmpl 1.12 to 2.0, and getting the following unhelpful error:

internal cmpl error: no suitable index value in SetIterator::isScalarIn()

Attached is the 1.12 model and my attempt at converting to 2.0

If it's a problem in my model, I'd ask for a better error message to indicate where the error is.

[ssincome v2.cmpl.txt](https://github.com/coin-or/Cmpl/files/7130605/ssincome.v2.cmpl.txt)
[ssincome.cmpl.txt](https://github.com/coin-or/Cmpl/files/7130606/ssincome.cmpl.txt)

**Comment by MikeSteglich** [comment]
I tested your problem with CMPL2 on macOS (M1) and got a result without any errors. Which operating system are you working with?

**Comment by MikeSteglich** [comment]
Did you use the beta version or the official release?

**Comment by snicolai** [comment]
The release version Coliop 4.2.0 on a 2014 Intel MacBook pro running Big Sur 11.5.2.

**Comment by MikeSteglich** [comment]
I also tested it on a Mac Pro Mid 2012 with macOS 10.14.6 and I found a result. In the attachment you can find the CMPL file and the solution.

[ssincomev2.zip](https://github.com/coin-or/Cmpl/files/7137273/ssincomev2.zip)

**Comment by snicolai-blog** [comment]
It still fails for me.  I finally got some time to investigate further.  It looks like an uninitialized memory problem.

with these changes in the makefiles, running on an Apple Silicon mac:

```
git diff makefile src/makefile
diff --git a/makefile b/makefile
index 448497d..4ed07f6 100644
--- a/makefile
+++ b/makefile
@@ -1,10 +1,10 @@
 
 # Makefile for cmpl
 
-export CXX := g++
-#export CXX := clang
+#export CXX := g++
+export CXX := clang
 
-export CXXFLAGS := -std=c++14 -DSTANDALONE -DPROTO -DCHDIR -ggdb -w 
+export CXXFLAGS := -std=c++14 -DSTANDALONE -DPROTO -DCHDIR -w -O1 -g -fsanitize=address,undefined,implicit-conversion,bounds -fno-omit-frame-pointer
 
 #export CXXFLAGS := -DSTANDALONE -DPROTO -DCHDIR -ggdb -std=c++14 -Wall -Wno-parentheses
 #export CXXFLAGS := -DSTANDALONE -DPROTO -DCHDIR -ggdb -std=c++0x -Wall -Wno-parentheses
diff --git a/src/makefile b/src/makefile
index 1d64553..91766ad 100644
--- a/src/makefile
+++ b/src/makefile
@@ -29,7 +29,7 @@ SUBDIRS2 := Modules Extensions
 
 
 $(OUTPUT) : $(OBJS) subobjs
-       $(CXX) -o $(OUTPUT) $(OBJS) $(SUBDIRS1:%=%/*.o) $(SUBDIRS2:%=%/*/*.o) $(LIBS) -lpthread  
+       $(CXX) -v $(CXXFLAGS) -o $(OUTPUT) $(OBJS) $(SUBDIRS1:%=%/*.o) $(SUBDIRS2:%=%/*/*.o) $(LIBS) -lpthread -lc++
 
 all : $(OUTPUT)

```
and running compl with this command line:

```
export UBSAN_OPTIONS=print_stacktrace=1
bin/cmpl $HOME/Downloads/ssincomev2/ssincomev2.cmpl

```
I get the following output:


```
CMPL version: 2.0.0
Authors: Thomas Schleiff, Mike Steglich
Distributed under the GPLv3 

CMPL: Interpreting Cmpl code
CompilerUtil.hh:1090:95: runtime error: load of value 3200171710, which is not a valid value for type 'cmpl::ModificatorKey'
    #0 0x10486da04 in cmpl::ExprParseInfo::isControlCBAssign(cmpl::ModificatorKey&) CompilerUtil.hh:1090
    #1 0x10486cdc4 in cmpl::CompilerContext::compAssign(cmpl::SyntaxElement*, cmpl::ExprParseInfo*, cmpl::ExprParseInfo*) CompilerContext.cc:1182
    #2 0x1048c70d8 in cmpl::CMPL_Parser::parse() CMPL_Parser.yy:290
    #3 0x104858280 in cmpl::CompilerContext::parse() CompilerContext.cc:112
    #4 0x1048495a4 in cmpl::Compiler::run() Compiler.cc:345
    #5 0x104603cb0 in cmpl::MainControl::run() MainControl.cc:263
    #6 0x1045fe500 in cmpl::MainControl::run(cmpl::CmdLineOptList*) MainControl.cc:164
    #7 0x1045889d4 in cmpl::Start::run(cmpl::CmdLineOptList*, cmpl::MainData*) Start.cc:124
    #8 0x10458856c in main Start.cc:52
    #9 0x1067d90f0 in start+0x204 (dyld:arm64e+0x50f0)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior CompilerUtil.hh:1090:95 in 
CompilerContext.cc:1208:13: runtime error: load of value 3200171710, which is not a valid value for type 'cmpl::IntCode::IcType'
    #0 0x10486d054 in cmpl::CompilerContext::compAssign(cmpl::SyntaxElement*, cmpl::ExprParseInfo*, cmpl::ExprParseInfo*) CompilerContext.cc:1208
    #1 0x1048c70d8 in cmpl::CMPL_Parser::parse() CMPL_Parser.yy:290
    #2 0x104858280 in cmpl::CompilerContext::parse() CompilerContext.cc:112
    #3 0x1048495a4 in cmpl::Compiler::run() Compiler.cc:345
    #4 0x104603cb0 in cmpl::MainControl::run() MainControl.cc:263
    #5 0x1045fe500 in cmpl::MainControl::run(cmpl::CmdLineOptList*) MainControl.cc:164
    #6 0x1045889d4 in cmpl::Start::run(cmpl::CmdLineOptList*, cmpl::MainData*) Start.cc:124
    #7 0x10458856c in main Start.cc:52
    #8 0x1067d90f0 in start+0x204 (dyld:arm64e+0x50f0)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior CompilerContext.cc:1208:13 in 
CompilerUtil.cc:328:8: runtime error: load of value 3200171710, which is not a valid value for type 'cmpl::ModificatorKey'
    #0 0x104890fa0 in cmpl::AssignModificators::isControlCBAssign(cmpl::CompilerContext*, cmpl::LocationInfo*, cmpl::ModificatorKey&) CompilerUtil.cc:328
    #1 0x1048ec338 in cmpl::CompilerContext::assignModControlCB(cmpl::LocationInfo*) CompilerContext.hh:333
    #2 0x1048d75c8 in cmpl::CMPL_Parser::parse() CMPL_Parser.yy:302
    #3 0x104858280 in cmpl::CompilerContext::parse() CompilerContext.cc:112
    #4 0x1048495a4 in cmpl::Compiler::run() Compiler.cc:345
    #5 0x104603cb0 in cmpl::MainControl::run() MainControl.cc:263
    #6 0x1045fe500 in cmpl::MainControl::run(cmpl::CmdLineOptList*) MainControl.cc:164
    #7 0x1045889d4 in cmpl::Start::run(cmpl::CmdLineOptList*, cmpl::MainData*) Start.cc:124
    #8 0x10458856c in main Start.cc:52
    #9 0x1067d90f0 in start+0x204 (dyld:arm64e+0x50f0)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior CompilerUtil.cc:328:8 in 
internal cmpl error: no suitable index value in SetIterator::isScalarIn()

```
Looks like there a number of places that ModificationKeys are not initialized before being tested.

For example, the first one is CompilerContext:

```
	unsigned CompilerContext::compAssign(SyntaxElement *elem, ExprParseInfo *expLhs, ExprParseInfo *expRhs)
	{
		unsigned a = _codeCnt;
		ExprParseInfo *e = (expLhs ?: expRhs);
		IntCode::IcElem *p;

		// codeblock control has own statements
		ModificatorKey cb;
		if (e->isControlCBAssign(cb)) {     // <-- not initialized on previous line, but tested here.
			return compControlCB(elem, cb, expLhs, (expRhs ? true : false));
		}

```
